services:
  prediction-service:
    build: .
    ports:
      - "9779:9779"
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app
      - CSV_PATH=/app/1806126.csv
      - MODEL_PATH=/app/model.pkl
    restart: always
